version: "3.9"
services:
  hello-world:
    image: chuckwired/port-tutorial:latest
    command: /usr/bin/nodejs /home/hello-world/app.js
    expose: 
      - "3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hello-world
    ports:
      - "4004:4004"
   